name: fngryboi
description: Dev, Modding, Games, VR.
meta_description:

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
about: 'about.html'
portfolio: 'portfolio.html'
domain_name: 'http://fngryboi.github.io/'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://fngryboi.github.io'
author:         'fngryboi'

# General Jekyll Config
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
