title: fngryboi
description: My place where I can ramble on...
baseurl: ""
url: "https://fngryboi.github.io"
github_username: fngryboi
author: fngryboi

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: twitter
social_username: fngryboi

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: custom

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed