title: Casper Alexis
description: Hi! I'm Casper Alexis, a backend developer by trade and a game developer by night, spending my free time making a game called Project Barkeep.
baseurl: ""
url: "https://www.momeen.me"
#github_username: momeenme
author: Casper Alexis

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
twitter: itscasperalexis
instagram: itscasperalexis

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: momeen

# Build settings
markdown: kramdown

sass:
    style: compressed

plugins:
  - jekyll-feed