name: fngryboi
description: Devendeavors, Modding, VR, Games
meta_description:

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: 'http://fngryboi.github.io/'
about: 'about.html'
domain_name: 'http://fngryboi.github.io/'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://fngryboi.github.io'
author:         'fngryboi'

# General Jekyll Config
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
