title: Momeen
description: Hi! I'm Casper 'Momeen' Strand, working as a web developer by day and spending the evenings developing my dream video game which is yet to be revealed.
baseurl: ""
url: "https://www.momeen.me"
#github_username: momeenme
author: Momeen

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: twitter
social_username: momeenme

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: momeen

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed